version: "3.9"
services:
  db:
    image: postgres:14
    container_name: label-studio-db
    ports:
      - 5434:5432
    volumes:
      - psql-store:/var/lib/postgresql/data
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/labelstudio
      - POSTGRES_DB=labelstudio
      - POSTGRES_PASSWORD=password
    networks:
      - default_network
volumes:
  psql-store:
networks:
  default_network:
